apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: worker-app
  template:
    metadata:
      name: worker-app
      labels:
        name: worker-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
    